# Generated by Django 3.0.4 on 2020-07-05 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcadamicYear', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('regNo', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=100)),
                ('attnd', models.FloatField(default=100.0)),
                ('Year', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True)),
                ('Sem', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2')], null=True)),
                ('subject1', models.CharField(max_length=100, null=True)),
                ('marks1', models.IntegerField(blank=True, default=0, null=True)),
                ('subject2', models.CharField(max_length=100, null=True)),
                ('marks2', models.IntegerField(blank=True, default=0, null=True)),
                ('subject3', models.CharField(max_length=100, null=True)),
                ('marks3', models.IntegerField(blank=True, default=0, null=True)),
                ('joinedYear', models.IntegerField()),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcadamicYear', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('regNo', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=100)),
                ('attnd', models.FloatField(default=100.0)),
                ('Year', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True)),
                ('Sem', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2')], null=True)),
                ('subject1', models.CharField(max_length=100, null=True)),
                ('marks1', models.IntegerField(blank=True, default=0, null=True)),
                ('subject2', models.CharField(max_length=100, null=True)),
                ('marks2', models.IntegerField(blank=True, default=0, null=True)),
                ('subject3', models.CharField(max_length=100, null=True)),
                ('marks3', models.IntegerField(blank=True, default=0, null=True)),
                ('joinedYear', models.IntegerField()),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
