# Generated by Django 3.0.4 on 2020-07-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstudent',
            name='attnd',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
        migrations.AlterField(
            model_name='currentstudent',
            name='joinedYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentstudent',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentstudent',
            name='regNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentstudent',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=100, null=True),
        ),
    ]
