# Generated by Django 3.0.4 on 2020-07-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200708_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstudent',
            name='subject1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentstudent',
            name='subject2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentstudent',
            name='subject3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
