# Generated by Django 3.0.4 on 2020-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200709_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstudent',
            name='profile_pic',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
