# Generated by Django 3.0.4 on 2020-07-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200710_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstudent',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='pictures'),
        ),
    ]
